iso:
  name: Bressan2012
  survey: des
jobs: 20
output:
  log_dir: log_dir
  results_dir: results_dir
  save_dir: plot_dir
survey:
  band_1: G
  band_2: R
  basis_1: RA
  basis_2: DEC
  datadir: /data/des40.b/data/y6a1/gold/1.1/healpix
  fracdet: null
  mag: SOF_PSF_MAG_{}
  mag_err: SOF_PSF_MAG_ERR_{}
  mag_max: 24.5
  name: des
  nside: 32
  quality: SOF_PSF_MAG_G < 24.5
  stars: WAVG_SPREAD_MODEL_G < 0.003 + SPREADERR_MODEL_G
